

public class Main {

    public static void main(String[] args)
    {
	    Deck Breya = new Deck();

	    Card Tezzeret= new Card("","", 5, "Planeswalker", Colors.BLUE, "Tezzert,the Seeker",false);
			Breya.aDeck.add(Tezzeret);
	    Card Daretti = new Card("","", 4, "Planeswalker", Colors.RED, "Daretti,Scrap Savant", false);
			Breya.aDeck.add(Daretti);
	    Card BreyaES = new Card("4", "4", 4, "Legendary Artifact Creature", Colors.YORE, "Breya,Etherium Shaper", true);
			Breya.aDeck.add(BreyaES);
		Card Swords = new Card("", "", 1, "Sorcery", Colors.WHITE, "Swords to Plowshares", false);
			Breya.aDeck.add(Swords);
		Card Grim = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Grim Monolith", false);
			Breya.aDeck.add(Grim);
		Card Manav = new Card("", "", 1, "Artifact", Colors.COLORLESS, "Mana Vault", false);
		 	Breya.aDeck.add(Manav);
		Card Sol = new Card("", "", 1, "Artifact", Colors.COLORLESS, "Sol Ring", false);
			Breya.aDeck.add(Sol);
		Card Ichor = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Ichor Wellspring", false);
			Breya.aDeck.add(Ichor);
		Card Counter = new Card("", "", 2, "Instant", Colors.BLUE, "Counterspell", false);
			Breya.aDeck.add(Counter);
		Card Trash = new Card("", "", 3, "Sorcery", Colors.RED, "Trash for Treasure", false);
			Breya.aDeck.add(Trash);
		Card Whir = new Card("", "", 3, "Instant", Colors.BLUE,"Whir of Invention", false);
			Breya.aDeck.add(Whir);
		Card Shimmer = new Card("2", "2", 3, "Artifact Creature", Colors.COLORLESS, "Shimmer Myr", false);
			Breya.aDeck.add(Shimmer);
		Card Fair = new Card("", "", 0, "Land", Colors.NONE,"Inventors Fair", false);
		 	Breya.aDeck.add(Fair);
		Card Shrine = new Card("", "", 0, "Land", Colors.NONE,"Godless Shrine", false);
			Breya.aDeck.add(Shrine);
		Card Watery = new Card("", "", 0, "Land", Colors.NONE, "Watery Grave", false);
			Breya.aDeck.add(Watery);
		Card Vents = new Card("", "", 0, "Land", Colors.NONE, "Steam Vents", false);
			Breya.aDeck.add(Vents);
		Card Crypt = new Card("", "", 0, "Land", Colors.NONE, "Blood Crypt", false);
			Breya.aDeck.add(Crypt);
		Card Clock = new Card("", "", 4, "Artifact", Colors.COLORLESS, "Unwinding Clock", false);
			Breya.aDeck.add(Clock);
		Card Den = new Card("", "", 0, "Land", Colors.NONE,"Ancient Dun", false);
			Breya.aDeck.add(Den);
		Card Sanctum = new Card("", "", 0, "Land", Colors.NONE, "Arcane Sanctum", false);
			Breya.aDeck.add(Sanctum);
		Card Ruin = new Card("", "", 0, "Land", Colors.NONE, "Buried Ruin", false);
			Breya.aDeck.add(Ruin);
		Card Command = new Card("", "", 0, "Land", Colors.NONE, "Command Tower", false);
			Breya.aDeck.add(Command);
		Card Crumbling = new Card("", "", 0, "Land", Colors.NONE, "Crumbling Necropolis", false);
			Breya.aDeck.add(Crumbling);
		Card Citadel = new Card("", "", 0, "Land", Colors.NONE, "Darksteel Citadel", false);
			Breya.aDeck.add(Citadel);
		Card Wilds = new Card("", "", 0, "Land", Colors.NONE, "Evolving Wilds", false);
			Breya.aDeck.add(Wilds);
		Card Orchard = new Card("", "", 0, "Land", Colors.NONE, "Exotic Orchard", false);
			Breya.aDeck.add(Orchard);
		Card Furnace = new Card("", "", 0, "Land", Colors.NONE, "Great Furnace", false);
			Breya.aDeck.add(Furnace);
		Card Island1 = new Card("", "", 0, "Land", Colors.NONE, "Island", false);
			Breya.aDeck.add(Island1);
		Card Island2 = new Card("", "", 0, "Land", Colors.NONE, "Island", false);
			Breya.aDeck.add(Island2);
		Card Island3 = new Card("", "", 0, "Land", Colors.NONE, "Island", false);
			Breya.aDeck.add(Island3);
		Card Island4 = new Card("", "", 0, "Land", Colors.NONE, "Island", false);
			Breya.aDeck.add(Island4);
		Card Mountain1 = new Card("", "", 0, "Land", Colors.NONE, "Mountain", false);
			Breya.aDeck.add(Mountain1);
		Card Mountain2 = new Card("", "", 0, "Land", Colors.NONE, "Mountain", false);
			Breya.aDeck.add(Mountain2);
		Card Mystic = new Card("", "", 0, "Land", Colors.NONE, "Mystic Monastery", false);
			Breya.aDeck.add(Mystic);
		Card Nomad = new Card("", "", 0, "Land", Colors.NONE, "Nomad Outpost", false);
			Breya.aDeck.add(Nomad);
		Card Plains1 = new Card("", "", 0, "Land", Colors.NONE, "Plains", false);
			Breya.aDeck.add(Plains1);
		Card Plains2 = new Card("", "", 0, "Land", Colors.NONE, "Plains", false);
			Breya.aDeck.add(Plains2);
		Card Plains3 = new Card("", "", 0, "Land", Colors.NONE, "Plains", false);
			Breya.aDeck.add(Plains3);
		Card Sacred = new Card("", "", 0, "Land", Colors.NONE, "Sacred Foundry", false);
			Breya.aDeck.add(Sacred);
		Card Seat = new Card("", "", 0, "Land", Colors.NONE, "Seat of the Synod", false);
			Breya.aDeck.add(Seat);
		Card Spire = new Card("", "", 0, "Land", Colors.NONE, "Spire of Industry", false);
			Breya.aDeck.add(Spire);
		Card Swamp1 = new Card("", "", 0, "Land", Colors.NONE, "Swamp", false);
			Breya.aDeck.add(Swamp1);
		Card Swamp2 = new Card("", "", 0, "Land", Colors.NONE, "Swamp", false);
			Breya.aDeck.add(Swamp2);
		Card Swamp3 = new Card("", "", 0, "Land", Colors.NONE, "Swamp", false);
			Breya.aDeck.add(Swamp3);
		Card Expanse = new Card("", "", 0, "Land", Colors.NONE, "Terramorphic Expanse", false);
			Breya.aDeck.add(Expanse);
		Card Vault = new Card("", "", 0, "Land", Colors.NONE, "Vault of Whispers", false);
			Breya.aDeck.add(Vault);
		Card Fountain = new Card("", "", 0, "Land", Colors.NONE, "Hallowed Fountain", false);
			Breya.aDeck.add(Fountain);
		Card Fabricate = new Card("", "", 3, "Sorcery", Colors.BLUE, "Fabricate", false);
			Breya.aDeck.add(Fabricate);
		Card Vaults = new Card("", "", 6, "Sorcery", Colors.WHITE, "Open the Vaults", false);
			Breya.aDeck.add(Vaults);
		Card Scrap = new Card("", "", 5, "Sorcery", Colors.RED, "Scrap Mastery", false);
			Breya.aDeck.add(Scrap);
		Card Transmute = new Card("", "", 2, "Sorcery", Colors.BLUE, "Transmute Artifact", false);
			Breya.aDeck.add(Transmute);
		Card Saheeli = new Card("", "", 3, "Planeswalker", Colors.IZZET, "Saheeli, Sublime Artificer", false);
			Breya.aDeck.add(Saheeli);
		Card Tezzeret2 = new Card("", "", 6, "Planeswalker", Colors.DIMIR, "Tezzeret, Master of the Bridge", false);
			Breya.aDeck.add(Tezzeret2);
		Card Arcane = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Arcane Signet", false);
			Breya.aDeck.add(Arcane);
		Card Altar = new Card("", "", 3, "Artifact", Colors.COLORLESS, "Ashnod's Altar", false);
			Breya.aDeck.add(Altar);
		Card Azorius = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Azorius Signet", false);
			Breya.aDeck.add(Azorius);
		Card Lantern = new Card("", "", 3, "Artifact", Colors.COLORLESS, "Chromatic Lantern", false);
			Breya.aDeck.add(Lantern);
		Card Sphere = new Card("", "", 3, "Artifact", Colors.COLORLESS, "Commander's Sphere", false);
			Breya.aDeck.add(Sphere);
		Card Plating = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Cranial Plating", false);
			Breya.aDeck.add(Plating);
		Card Forge = new Card("", "", 9, "Artifact", Colors.COLORLESS, "Darksteel Forge", false);
			Breya.aDeck.add(Forge);
		Card Dimir = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Dimir Signet", false);
			Breya.aDeck.add(Dimir);
		Card Fellwar = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Fellwar Stone", false);
			Breya.aDeck.add(Fellwar);
		Card Izzet = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Izzet Signet", false);
			Breya.aDeck.add(Izzet);
		Card Ironworks = new Card("", "", 4, "Artifact", Colors.COLORLESS, "Krark-Clan Ironworks", false);
			Breya.aDeck.add(Ironworks);
		Card MysticF = new Card("", "", 4, "Artifact", Colors.COLORLESS, "Mystic Forge", false);
			Breya.aDeck.add(MysticF);
		Card NevDisk = new Card("", "", 4, "Artifact", Colors.COLORLESS, "Nevinyrral's Disk", false);
			Breya.aDeck.add(NevDisk);
		Card Deathmantle = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Nim Deathmantle", false);
			Breya.aDeck.add(Deathmantle);
		Card Skullclamp = new Card("", "", 1, "Artifact", Colors.COLORLESS, "Skullclamp", false);
			Breya.aDeck.add(Skullclamp);
		Card Sword = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Sword of the Meek", false);
			Breya.aDeck.add(Sword);
		Card Foundry = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Thopter Foundry", false);
			Breya.aDeck.add(Foundry);
		Card Time = new Card("", "", 2, "Artifact", Colors.COLORLESS, "Time Sieve", false);
			Breya.aDeck.add(Time);
		Card Post = new Card("", "", 4, "Artifact", Colors.COLORLESS, "Trading Post", false);
			Breya.aDeck.add(Post);
		Card Rift = new Card("", "", 2, "Instant", Colors.BLUE, "Cyclonic Rift", false);
			Breya.aDeck.add(Rift);
		Card Tutor = new Card("", "", 1, "Instant", Colors.WHITE, "Enlightened Tutor", false);
			Breya.aDeck.add(Tutor);
		Card Mirrodin = new Card("", "", 3, "Enchantment", Colors.BLUE, "Mirrodin Besieged", false);
			Breya.aDeck.add(Mirrodin);
		Card Tithe = new Card("", "", 4, "Enchantment", Colors.WHITE, "Smothering Tithe", false);
			Breya.aDeck.add(Tithe);
		Card Storm = new Card("", "", 4, "Enchantment", Colors.IZZET, "Storm the Vault", false);
			Breya.aDeck.add(Storm);
		Card Spy = new Card("", "", 4, "Enchantment", Colors.BLUE, "Thopter Spy Network", false);
			Breya.aDeck.add(Spy);
		Card Strix = new Card("1", "1", 2, "Artifact Creature", Colors.DIMIR, "Baleful Strix", false);
			Breya.aDeck.add(Strix);
		Card Engineer = new Card("1", "3", 2, "Creature", Colors.BLUE, "Chief Engineer", false);
			Breya.aDeck.add(Engineer);
		Card Displacer = new Card("3", "3", 3, "Creature", Colors.WHITE, "Eldrazi Displacer", false);
			Breya.aDeck.add(Displacer);
		Card Emry = new Card("1", "2", 3, "Legendary Creature", Colors.BLUE, "Emry, Lurker of the Loch", false);
			Breya.aDeck.add(Emry);
		Card Sculptor = new Card("1", "2", 2, "Artifact Creature", Colors.BLUE, "Etherium Sculptor", false);
			Breya.aDeck.add(Sculptor);
		Card Adjudicator = new Card("4", "4", 5, "Artifact Creature", Colors.BLUE, "Ethersworn Adjudicator", false);
			Breya.aDeck.add(Adjudicator);
		Card Welder = new Card("1", "1", 1, "Creature", Colors.RED, "Goblin Welder", false);
			Breya.aDeck.add(Welder);
		Card Hanna = new Card("1", "2", 3, "Legendary Creature", Colors.AZORIUS, "Hanna, Ship's Navigator", false);
			Breya.aDeck.add(Hanna);
		Card Tyrant = new Card("6", "5", 6, "Creature", Colors.RED, "Hellkite Tyrant", false);
			Breya.aDeck.add(Tyrant);
		Card Jhoira = new Card("3", "3", 4, "Legendary Creature", Colors.IZZET, "Jhoira, Weatherlight Captain", false);
			Breya.aDeck.add(Jhoira);
		Card Forgemaster = new Card("3", "5", 5, "Artifact Creature", Colors.COLORLESS, "Kuldotha Forgemaster", false);
			Breya.aDeck.add(Forgemaster);
		Card Master = new Card("*", "*", 3, "Artifact Creature", Colors.BLUE, "Master of Etherium", false);
			Breya.aDeck.add(Master);
		Card Battlesphere = new Card("4", "7", 7, "Artifact Creature", Colors.COLORLESS, "Myr Battlesphere", false);
			Breya.aDeck.add(Battlesphere);
		Card Retriever = new Card("1", "1", 2, "Artifact Creature", Colors.COLORLESS, "Myr Retriever", false);
			Breya.aDeck.add(Retriever);
		Card Padeem = new Card("1", "4", 4, "Legendary Creature", Colors.BLUE, "Padeem, Consul of Innovation", false);
			Breya.aDeck.add(Padeem);
		Card Metamorph = new Card("0", "0", 4, "Artifact Creature", Colors.BLUE, "Phyrexian Metamorph", false);
			Breya.aDeck.add(Metamorph);
		Card Sai = new Card("1", "4", 3, "Legendary Creature", Colors.BLUE, "Sai, Master Thopterist", false);
			Breya.aDeck.add(Sai);
		Card Sharuum = new Card("5", "5", 6, "Legendary Artifact Creature", Colors.ESPER, "Sharuum the Hegemon", false);
			Breya.aDeck.add(Sharuum);
		Card Sad = new Card("2", "2", 4, "Artifact Creature", Colors.COLORLESS, "Solemn Simulacrum", false);
			Breya.aDeck.add(Sad);
		Card Sphinx = new Card("3", "3", 5, "Artifact Creature", Colors.DIMIR, "Sphinx Summoner", false);
			Breya.aDeck.add(Sphinx);
		Card Assembly = new Card("5", "5", 6, "Artifact Creature", Colors.COLORLESS, "Thopter Assembly", false);
			Breya.aDeck.add(Assembly);
		Card Mage = new Card("2", "2", 3, "Creature", Colors.BLUE, "Tinket Mage", false);
			Breya.aDeck.add(Mage);

	    //System.out.println(Breya.ShowDeck());
	    System.out.println(Breya.ShowLands());
	    System.out.println(Breya.ShowCreatures());
	    System.out.println(Breya.ShowArtifacts());
	    System.out.println(Breya.ShowEnchantments());
	    System.out.println(Breya.ShowInstants());
	    System.out.println(Breya.ShowSorceries());
	    System.out.println(Breya.ShowPlaneswakers());


    }
}
